name: OpenAPI Generator Validate and Generate
on: [pull_request, push, workflow_dispatch]
jobs:
  openapi-generator-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bundle Spec
        uses: docker://redocly/cli:latest
        with:
          args: bundle --dereferenced openapi.yaml -o bundle.yaml
      - name: OpenAPI Generator Validate
        uses: docker://openapitools/openapi-generator-cli:latest
        with:
          args: validate -i bundle.yaml
        env:
          JAVA_OPTS: -DmaxYamlCodePoints=99999999 # Required or else openapi-generator will run out of memory
      - name: OpenAPI Generator Generate - Setup
        run: |
          mkdir client-python
          cp .openapi-generator/.openapi-generator-ignore client-python
      - name: OpenAPI Generator Generate
        uses: docker://openapitools/openapi-generator-cli:latest
        with:
          args: generate -i bundle.yaml -g python -o client-python
        env:
          JAVA_OPTS: -DmaxYamlCodePoints=99999999 # Required or else openapi-generator will run out of memory
      - name: List Contents of Generated Client
        run: |
          find client-python
      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Python Build and Test
        run: |
          cd client-python
          pip install -r requirements.txt
          python setup.py build
